// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { AddressListData, AddressListResponse, AddressCreateData, AddressCreateResponse, AddressDestroyData, AddressDestroyResponse, AddressRetrieveData, AddressRetrieveResponse, AddressPartialUpdateData, AddressPartialUpdateResponse, AddressUpdateData, AddressUpdateResponse, AptsListData, AptsListResponse, AptsCreateData, AptsCreateResponse, AptsDestroyData, AptsDestroyResponse, AptsRetrieveData, AptsRetrieveResponse, AptsPartialUpdateData, AptsPartialUpdateResponse, AptsUpdateData, AptsUpdateResponse } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const addressList = <ThrowOnError extends boolean = false>(options?: Options<AddressListData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<AddressListResponse, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            },
            {
                scheme: 'basic',
                type: 'http'
            }
        ],
        url: '/address/',
        ...options
    });
};

export const addressCreate = <ThrowOnError extends boolean = false>(options: Options<AddressCreateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AddressCreateResponse, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            },
            {
                scheme: 'basic',
                type: 'http'
            }
        ],
        url: '/address/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const addressDestroy = <ThrowOnError extends boolean = false>(options: Options<AddressDestroyData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<AddressDestroyResponse, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            },
            {
                scheme: 'basic',
                type: 'http'
            }
        ],
        url: '/address/{hashid}/',
        ...options
    });
};

export const addressRetrieve = <ThrowOnError extends boolean = false>(options: Options<AddressRetrieveData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<AddressRetrieveResponse, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            },
            {
                scheme: 'basic',
                type: 'http'
            }
        ],
        url: '/address/{hashid}/',
        ...options
    });
};

export const addressPartialUpdate = <ThrowOnError extends boolean = false>(options: Options<AddressPartialUpdateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<AddressPartialUpdateResponse, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            },
            {
                scheme: 'basic',
                type: 'http'
            }
        ],
        url: '/address/{hashid}/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const addressUpdate = <ThrowOnError extends boolean = false>(options: Options<AddressUpdateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<AddressUpdateResponse, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            },
            {
                scheme: 'basic',
                type: 'http'
            }
        ],
        url: '/address/{hashid}/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const aptsList = <ThrowOnError extends boolean = false>(options?: Options<AptsListData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<AptsListResponse, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            },
            {
                scheme: 'basic',
                type: 'http'
            }
        ],
        url: '/apts/',
        ...options
    });
};

export const aptsCreate = <ThrowOnError extends boolean = false>(options: Options<AptsCreateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AptsCreateResponse, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            },
            {
                scheme: 'basic',
                type: 'http'
            }
        ],
        url: '/apts/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const aptsDestroy = <ThrowOnError extends boolean = false>(options: Options<AptsDestroyData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<AptsDestroyResponse, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            },
            {
                scheme: 'basic',
                type: 'http'
            }
        ],
        url: '/apts/{hashid}/',
        ...options
    });
};

export const aptsRetrieve = <ThrowOnError extends boolean = false>(options: Options<AptsRetrieveData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<AptsRetrieveResponse, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            },
            {
                scheme: 'basic',
                type: 'http'
            }
        ],
        url: '/apts/{hashid}/',
        ...options
    });
};

export const aptsPartialUpdate = <ThrowOnError extends boolean = false>(options: Options<AptsPartialUpdateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<AptsPartialUpdateResponse, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            },
            {
                scheme: 'basic',
                type: 'http'
            }
        ],
        url: '/apts/{hashid}/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const aptsUpdate = <ThrowOnError extends boolean = false>(options: Options<AptsUpdateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<AptsUpdateResponse, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            },
            {
                scheme: 'basic',
                type: 'http'
            }
        ],
        url: '/apts/{hashid}/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};