// This file is auto-generated by @hey-api/openapi-ts

export type AddressReadable = {
    readonly hashid: string;
    address: string;
    complement: string;
    poggers: string;
    cep?: string | null;
};

export type AddressWritable = {
    address: string;
    complement: string;
    poggers: string;
    cep?: string | null;
};

export type AptReadable = {
    readonly hashid: string;
    address: AddressReadable;
    image: string;
    description?: string;
    value: string;
    bedrooms: number;
    living_rooms: number;
    bathrooms: number;
    suites?: number;
    size: string;
    property_type: PropertyTypeEnum;
    region: number;
};

export type AptWritable = {
    address: AddressWritable;
    image: string;
    description?: string;
    value: string;
    bedrooms: number;
    living_rooms: number;
    bathrooms: number;
    suites?: number;
    size: string;
    property_type: PropertyTypeEnum;
    region: number;
};

export type PaginatedAddressListReadable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<AddressReadable>;
};

export type PaginatedAddressListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<AddressWritable>;
};

export type PaginatedAptListReadable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<AptReadable>;
};

export type PaginatedAptListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<AptWritable>;
};

export type PatchedAddressReadable = {
    readonly hashid?: string;
    address?: string;
    complement?: string;
    poggers?: string;
    cep?: string | null;
};

export type PatchedAddressWritable = {
    address?: string;
    complement?: string;
    poggers?: string;
    cep?: string | null;
};

export type PatchedAptReadable = {
    readonly hashid?: string;
    address?: AddressReadable;
    image?: string;
    description?: string;
    value?: string;
    bedrooms?: number;
    living_rooms?: number;
    bathrooms?: number;
    suites?: number;
    size?: string;
    property_type?: PropertyTypeEnum;
    region?: number;
};

export type PatchedAptWritable = {
    address?: AddressWritable;
    image?: string;
    description?: string;
    value?: string;
    bedrooms?: number;
    living_rooms?: number;
    bathrooms?: number;
    suites?: number;
    size?: string;
    property_type?: PropertyTypeEnum;
    region?: number;
};

/**
 * * `HOUSE` - House
 * * `APARTMENT` - Apartment
 */
export type PropertyTypeEnum = 'HOUSE' | 'APARTMENT';

export type AddressListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
    };
    url: '/address/';
};

export type AddressListResponses = {
    200: PaginatedAddressListReadable;
};

export type AddressListResponse = AddressListResponses[keyof AddressListResponses];

export type AddressCreateData = {
    body: AddressWritable;
    path?: never;
    query?: never;
    url: '/address/';
};

export type AddressCreateResponses = {
    201: AddressReadable;
};

export type AddressCreateResponse = AddressCreateResponses[keyof AddressCreateResponses];

export type AddressDestroyData = {
    body?: never;
    path: {
        hashid: string;
    };
    query?: never;
    url: '/address/{hashid}/';
};

export type AddressDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type AddressDestroyResponse = AddressDestroyResponses[keyof AddressDestroyResponses];

export type AddressRetrieveData = {
    body?: never;
    path: {
        hashid: string;
    };
    query?: never;
    url: '/address/{hashid}/';
};

export type AddressRetrieveResponses = {
    200: AddressReadable;
};

export type AddressRetrieveResponse = AddressRetrieveResponses[keyof AddressRetrieveResponses];

export type AddressPartialUpdateData = {
    body?: PatchedAddressWritable;
    path: {
        hashid: string;
    };
    query?: never;
    url: '/address/{hashid}/';
};

export type AddressPartialUpdateResponses = {
    200: AddressReadable;
};

export type AddressPartialUpdateResponse = AddressPartialUpdateResponses[keyof AddressPartialUpdateResponses];

export type AddressUpdateData = {
    body: AddressWritable;
    path: {
        hashid: string;
    };
    query?: never;
    url: '/address/{hashid}/';
};

export type AddressUpdateResponses = {
    200: AddressReadable;
};

export type AddressUpdateResponse = AddressUpdateResponses[keyof AddressUpdateResponses];

export type AptsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
    };
    url: '/apts/';
};

export type AptsListResponses = {
    200: PaginatedAptListReadable;
};

export type AptsListResponse = AptsListResponses[keyof AptsListResponses];

export type AptsCreateData = {
    body: AptWritable;
    path?: never;
    query?: never;
    url: '/apts/';
};

export type AptsCreateResponses = {
    201: AptReadable;
};

export type AptsCreateResponse = AptsCreateResponses[keyof AptsCreateResponses];

export type AptsDestroyData = {
    body?: never;
    path: {
        hashid: string;
    };
    query?: never;
    url: '/apts/{hashid}/';
};

export type AptsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type AptsDestroyResponse = AptsDestroyResponses[keyof AptsDestroyResponses];

export type AptsRetrieveData = {
    body?: never;
    path: {
        hashid: string;
    };
    query?: never;
    url: '/apts/{hashid}/';
};

export type AptsRetrieveResponses = {
    200: AptReadable;
};

export type AptsRetrieveResponse = AptsRetrieveResponses[keyof AptsRetrieveResponses];

export type AptsPartialUpdateData = {
    body?: PatchedAptWritable;
    path: {
        hashid: string;
    };
    query?: never;
    url: '/apts/{hashid}/';
};

export type AptsPartialUpdateResponses = {
    200: AptReadable;
};

export type AptsPartialUpdateResponse = AptsPartialUpdateResponses[keyof AptsPartialUpdateResponses];

export type AptsUpdateData = {
    body: AptWritable;
    path: {
        hashid: string;
    };
    query?: never;
    url: '/apts/{hashid}/';
};

export type AptsUpdateResponses = {
    200: AptReadable;
};

export type AptsUpdateResponse = AptsUpdateResponses[keyof AptsUpdateResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};